apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: collatz-frontend:latest
        imagePullPolicy: Always
        name: collatz-frontend
        ports:
          - containerPort: 8080
            protocol: TCP
