apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-frontend
  labels:
    app: dev-collatz
    app.kubernetes.io/part-of: dev-collatz
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: dev-collatz-frontend:latest
        imagePullPolicy: Always
        name: collatz-frontend
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: BACKEND
            value: dev-collatz-backend
