apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-backend
  labels:
    app: dev-collatz
    app.kubernetes.io/part-of: dev-collatz
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/dev-collatz-backend:latest
        imagePullPolicy: Always
        name: collatz-backend
        ports:
          - containerPort: 8081
            protocol: TCP
