namePrefix: dev-  

commonLabels:
  variant: development

commonAnnotations:
  # note: We are on dev now
  stage: development

bases:
- ../../base

patchesStrategicMerge:
  - deployment-frontend.yaml
  - deployment-backend.yaml
  - route.yaml