apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: collatz
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: dev-collatz-frontend
    weight: 100
  wildcardPolicy: None

  