apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/aodf/staging-collatz-frontend:latest'
        imagePullPolicy: Always
        name: collatz-frontend
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: BACKEND
            value: staging-collatz-backend
          - name: TESTE
            value: $(ARGOCD_APP_NAMESPACE) 