apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: staging-collatz-frontend:latest
        imagePullPolicy: Always
        name: collatz-frontend
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: BACKEND
            value: staging-collatz-backend