namePrefix: staging-

commonLabels:
  variant: staging

commonAnnotations:
  note: We are on staging now
  stage: staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-frontend.yaml
  - deployment-backend.yaml
  - build-frontend.yaml
  - build-backend.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - route.yaml
