apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: sdxsolutions.com

resources:
- deployment-frontend.yaml
- deployment-backend.yaml
- imagestream-frontend.yaml
- imagestream-backend.yaml
- build-frontend.yaml
- build-backend.yaml
- service-frontend.yaml
- service-backend.yaml
- route.yaml
