apiVersion: apps/v1
kind: Deployment
metadata:
  name: odf
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: odf
  template:
    metadata:
      labels:
        app: odf
    spec:
      containers:
        name: odf
          image: 'odf:v1'
            ports:
              containerPort: 8080
