kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: odf
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'odf:v1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'golang:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/epenedos/ODF-Calculator'
      ref: master
  runPolicy: Serial
