kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: build-frontend
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "staging-collatz-frontend:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "golang:latest"
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/epenedos/Collatz-conjecture.git"
      ref: main
    contextDir: collatz-fe
  triggers:
    - type: ConfigChange
  runPolicy: Serial
