apiVersion: apps/v1
kind: Deployment
metadata:
  name: collatz-frontend
  labels:
    app: prod-collatz
    app.kubernetes.io/part-of: prod-collatz
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: prod-collatz-frontend:latest
        imagePullPolicy: Always
        name: collatz-frontend
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: BACKEND
            value: prod-collatz-backend
